"""Layman-facing visualizations.

WHAT
----
Every figure here is designed so a NON-engineer can read it in 5 seconds:
    - one idea per chart
    - plain-English titles ("Which recipe learned the language best?")
    - explicit hints on the chart ("lower = better", "higher = faster")
    - concept cartoons for attention / RoPE / FlashAttention / BPE that
      show WHAT is computed, not formulas

WHY
----
The research goal is answering "WHY did the number change?" - and the
evidence only persuades if people who cannot read the code can read the
result. These charts are the lab's external interface.

WHERE
-----
Generated by the trainer (loss curves), by scripts/analyze.py (comparison
suite) and by notebooks/04_experiment_analysis.ipynb. All outputs are
PNG files saved next to the data they describe.
"""
from __future__ import annotations

import os
from typing import Dict, List, Optional

import matplotlib
matplotlib.use("Agg")  # headless-safe everywhere (Colab/Kaggle/local)
import matplotlib.pyplot as plt
import numpy as np

# Colorblind-friendly palette, fixed so charts are comparable across runs.
PALETTE = {
    "vanilla_learned": "#0072B2",   # blue   - A: classic + position table
    "vanilla_rope": "#D55E00",      # orange - B: classic + rotation
    "flash_learned": "#009E73",     # green  - C: flash + position table
    "flash_rope": "#CC79A7",        # purple - D: flash + rotation
}
VARIANT_LABELS = {
    "vanilla_learned": "A: Classic attention\n+ position table",
    "vanilla_rope": "B: Classic attention\n+ rotation (RoPE)",
    "flash_learned": "C: Flash attention\n+ position table",
    "flash_rope": "D: Flash attention\n+ rotation (RoPE)",
}
VARIANT_SHORT = {
    "vanilla_learned": "A", "vanilla_rope": "B",
    "flash_learned": "C", "flash_rope": "D",
}
_BIG = 16
_MED = 12


def _variant_key(entry: dict) -> str:
    # Normalize attention: the A/B/C/D labels treat flash_tiled and
    # flash_fused as the same experimental CELL (flash attention) - they
    # differ only in implementation, not in the ablation variable.
    attn = entry["attention"]
    if attn.startswith("flash"):
        attn = "flash"
    return f"{attn}_{entry['position']}"


def _color_of(key: str) -> str:
    return PALETTE.get(key, "#777777")


def _label_of(key: str) -> str:
    return VARIANT_LABELS.get(key, key.replace("_", " + "))


def _save(fig, path: str) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return path


# --------------------------------------------------------------------------
# 1. Loss curves - the basic training progress picture
# --------------------------------------------------------------------------
def plot_loss_curves_layman(run_dir: str, out_path: Optional[str] = None) -> Optional[str]:
    """Train/val loss vs tokens with plain-English annotations."""
    csv_path = os.path.join(run_dir, "metrics.csv")
    if not os.path.exists(csv_path):
        return None
    import csv
    tokens, train_l, val_l = [], [], []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                tokens.append(int(row["tokens_seen"]))
                train_l.append(float(row["train_loss"]))
                val_l.append(float(row["val_loss"]))
            except (ValueError, KeyError):
                continue
    if not tokens:
        return None
    if out_path is None:
        out_path = os.path.join(run_dir, "learning_progress.png")
    fig, ax = plt.subplots(figsize=(9, 5.5))
    ax.plot(tokens, train_l, color="#0072B2", lw=2.5,
            label="learning curve (training)")
    ax.plot(tokens, val_l, color="#D55E00", lw=2.5,
            label="checkup curve (unseen text)")
    ax.set_xlabel("amount of text read (tokens)", fontsize=_MED)
    ax.set_ylabel("mistake level (loss)", fontsize=_MED)
    ax.set_title("The model makes fewer mistakes as it reads more text",
                 fontsize=_BIG, pad=12)
    ax.annotate("lower = better", xy=(0.98, 0.9), xycoords="axes fraction",
                ha="right", fontsize=_MED, color="#555555")
    ax.legend(fontsize=_MED, frameon=False)
    ax.grid(alpha=0.25)
    ax.set_ylim(0, None)
    fig.tight_layout()
    return _save(fig, out_path)


# --------------------------------------------------------------------------
# 2. Concept cartoons - one idea each
# --------------------------------------------------------------------------
def plot_attention_concept(out_path: str) -> str:
    """WHAT attention does, in three panels, no formulas.

    Panel 1: compare - score how useful each EARLIER word is for now.
    Panel 2: normalize - turn scores into percentages (softmax).
    Panel 3: gather - blend earlier words' meanings by those percentages.
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6))
    words = ["The", "cat", "sat", "on", "the", "mat"]
    n = len(words)
    for ax, title, sub in zip(
            axes,
            ["1. COMPARE", "2. TURN INTO %", "3. GATHER"],
            ["How useful is each\nearlier word for\nreading the next one?",
             "Convert the scores into\npercentages that add up\nto 100%.",
             "Blend the earlier words'\nmeanings by those\npercentages."]):
        ax.set_xlim(-0.5, n - 0.5)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.set_title(title, fontsize=_BIG, color="#0072B2")
        if title.startswith("1."):
            heights = np.linspace(0.15, 0.9, n)
            for i, (w, h) in enumerate(zip(words, heights)):
                ax.bar(i, h, color="#66A6CC", alpha=0.9)
                ax.text(i, h + 0.05, f"{h:.0%}", ha="center", fontsize=10)
        elif title.startswith("2."):
            vals = np.linspace(0.05, 0.45, n)
            vals = vals / vals.sum()
            for i, (w, v) in enumerate(zip(words, vals)):
                ax.bar(i, v, color="#D55E00", alpha=0.9)
                ax.text(i, v + 0.05, f"{v:.0%}", ha="center", fontsize=10)
        else:
            sizes = np.linspace(400, 1200, n)
            for i, (w, s) in enumerate(zip(words, sizes)):
                ax.scatter([i], [0.5], s=s, color="#009E73", alpha=0.85)
                ax.text(i, 0.5, w, ha="center", va="center", fontsize=10,
                        color="white")
            ax.text(n - 0.5, 0.9, "size = share of\nattention", ha="center",
                    fontsize=10, color="#009E73")
        for i, w in enumerate(words):
            ax.text(i, -0.02, w, ha="center", fontsize=11)
        ax.text(0, -0.16, sub, ha="left", fontsize=_MED, color="#333333")
    fig.suptitle("How attention works: every word looks back, scores its "
                 "neighbours, and blends their meanings",
                 fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_rope_concept(out_path: str) -> str:
    """RoPE cartoon: position = rotation angle.

    Left: one token's arrow rotated differently for each position in the
    sentence. Right: two arrows whose angle difference stays the SAME for
    the same distance apart - that constant difference is how the model
    "sees" relative position.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5))
    # Left: absolute rotation grows with position
    ax = axes[0]
    ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2)
    ax.axhline(0, color="grey", lw=0.5); ax.axvline(0, color="grey", lw=0.5)
    for pos in range(6):
        ang = pos * 0.55
        x, y = np.cos(ang), np.sin(ang)
        ax.arrow(0, 0, x, y, head_width=0.06, head_length=0.08,
                 fc=PALETTE["vanilla_rope"], ec=PALETTE["vanilla_rope"],
                 lw=2, length_includes_head=True)
        ax.text(x * 1.22, y * 1.22, f"word {pos}", fontsize=11, ha="center",
                color="#D55E00")
    ax.set_title("Each position = a different\nrotation of the same arrow",
                 fontsize=_BIG, color="#D55E00")
    ax.set_aspect("equal"); ax.axis("off")
    # Right: relative angle is constant for the same distance
    ax = axes[1]
    ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2)
    ax.axhline(0, color="grey", lw=0.5); ax.axvline(0, color="grey", lw=0.5)
    for pos, col in [(2, "#0072B2"), (5, "#D55E00")]:
        ang = pos * 0.55
        ax.arrow(0, 0, np.cos(ang), np.sin(ang), head_width=0.06,
                 head_length=0.08, fc=col, ec=col, lw=2.5,
                 length_includes_head=True)
        ax.text(np.cos(ang) * 1.2, np.sin(ang) * 1.2,
                f"word {pos}", fontsize=11, ha="center", color=col)
    arc = plt.Arc((0, 0), 0.7, 0.7, angle=0, theta1=0, theta2=150,
                  color="#555555", lw=1.5, linestyle="--")
    ax.add_patch(arc)
    ax.text(0.55, 0.55, "same angle gap\n= same distance\napart", fontsize=11,
            ha="center", color="#555555")
    ax.set_title("Words the same distance apart\nalways see the same angle gap",
                 fontsize=_BIG, color="#0072B2")
    ax.set_aspect("equal"); ax.axis("off")
    fig.suptitle("Rotation positions (RoPE): where a word sits = how far its "
                 "meaning-arrow is turned", fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_flash_concept(out_path: str) -> str:
    """FlashAttention cartoon: giant score table vs one strip at a time.

    Left: the classic method materializes the FULL T x T comparison table
    (red, expensive). Right: flash works strip by strip, keeping only one
    strip in memory and updating a running result (green, cheap). Same
    final answer - the strip method is algebraically exact.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.2))
    T = 10
    grid = np.ones((T, T))
    ax = axes[0]
    ax.imshow(grid, cmap="Reds", vmin=0, vmax=1, interpolation="nearest")
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_xlabel("words so far", fontsize=_MED)
    ax.set_ylabel("current word", fontsize=_MED)
    ax.set_title("Classic attention: builds the\nWHOLE comparison table at once",
                 fontsize=_BIG, color="#8B0000")
    ax.text(0.5, -0.16, "10 x 10 = 100 boxes to remember", transform=ax.transAxes,
            ha="center", fontsize=_MED, color="#8B0000")
    ax = axes[1]
    ax.imshow(np.tril(np.ones((T, T))), cmap="Greens", vmin=0, vmax=1,
              interpolation="nearest")
    for j in range(T):
        ax.axvline(j + 0.5, color="white", lw=2.5)
    ax.axvspan(2.5, 3.5, color="#CC79A7", alpha=0.55)
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_xlabel("words so far", fontsize=_MED)
    ax.set_ylabel("current word", fontsize=_MED)
    ax.set_title("Flash attention: works through\nONE strip at a time",
                 fontsize=_BIG, color="#006400")
    ax.text(0.5, -0.16, "only 1 strip in memory at any moment",
            transform=ax.transAxes, ha="center", fontsize=_MED,
            color="#006400")
    ax.text(3, -1.6, "in use now", ha="center", fontsize=10, color="#CC79A7")
    fig.suptitle("FlashAttention: same final answer, far less memory - the "
                 "table is processed strip by strip", fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_bpe_concept(text: str, tokenizer, out_path: str) -> str:
    """BPE cartoon: how a sentence is chopped into reusable pieces.

    Each token is drawn as a coloured box; frequent words become ONE box,
    rare words get split into several smaller (still reusable) pieces.
    Caption states the compression: N characters -> M pieces.
    """
    ids = tokenizer.encode(text)
    pieces = [tokenizer.decode([i]) for i in ids]
    fig, ax = plt.subplots(figsize=(max(8, len(pieces) * 0.55), 3.6))
    ax.axis("off")
    x = 0.0
    cmap = plt.get_cmap("tab20")
    for k, piece in enumerate(pieces):
        w = max(0.32, len(piece) * 0.16)
        ax.add_patch(plt.Rectangle((x, 0.3), w - 0.03, 0.6,
                                   facecolor=cmap(k % 20), alpha=0.85,
                                   edgecolor="black"))
        ax.text(x + (w - 0.03) / 2, 0.6, piece.replace(" ", "␣"),
                ha="center", va="center", fontsize=10)
        x += w
    ax.set_xlim(0, x)
    ax.set_ylim(0, 1.1)
    ratio = len(text) / max(len(ids), 1)
    ax.text(0, -0.12,
            f"{len(text)} characters -> {len(ids)} reusable pieces "
            f"(each piece ~{ratio:.1f} characters)",
            fontsize=_MED, color="#333333")
    ax.set_title("How the tokenizer chops text into reusable pieces (BPE)",
                 fontsize=_BIG)
    return _save(fig, out_path)


# --------------------------------------------------------------------------
# 3. Comparison charts (the scientific core, rendered for everyone)
# --------------------------------------------------------------------------
def plot_comparison_quality(summaries: List[dict], out_path: str,
                            dataset_name: str = "") -> str:
    """Bar chart: best validation loss per variant, winner highlighted.

    'Lower = better' printed ON the chart; the winner's bar gets a star.
    """
    keys = [_variant_key(s) for s in summaries]
    vals = [s.get("best_val_loss", s.get("final_val_loss", 0.0)) for s in summaries]
    fig, ax = plt.subplots(figsize=(10, 5.8))
    x = np.arange(len(vals))
    colors = [_color_of(k) for k in keys]
    bars = ax.bar(x, vals, color=colors, width=0.55)
    best_i = int(np.argmin(vals))
    ax.scatter([best_i], [vals[best_i]], marker="*", s=420, color="#FFD700",
               edgecolor="black", zorder=5, label="winner")
    ax.set_xticks(x)
    ax.set_xticklabels([_label_of(k) for k in keys], fontsize=11)
    ax.set_ylabel("mistake level (best validation loss)", fontsize=_MED)
    ax.set_title(f"Which recipe learned {dataset_name or 'the text'} best?",
                 fontsize=_BIG, pad=12)
    ax.annotate("lower = better", xy=(0.98, 0.06), xycoords="axes fraction",
                ha="right", fontsize=_MED, color="#555555")
    for i, v in enumerate(vals):
        ax.text(i, v + 0.01 * max(vals), f"{v:.3f}", ha="center", fontsize=11)
    ax.legend(fontsize=_MED, loc="upper right", frameon=False)
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_comparison_efficiency(summaries: List[dict], out_path: str) -> str:
    """Two bars per variant: speed (higher=better) and memory (lower=better)."""
    keys = [_variant_key(s) for s in summaries]
    speeds = [s.get("tokens_per_sec", 0.0) for s in summaries]
    mems = [s.get("peak_gpu_mem_mb", 0.0) for s in summaries]
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12.5, 5.2))
    x = np.arange(len(keys))
    ax1.bar(x, speeds, color=[_color_of(k) for k in keys], width=0.55)
    ax1.set_xticks(x)
    ax1.set_xticklabels([VARIANT_SHORT[k] for k in keys], fontsize=13)
    ax1.set_title("Speed: text read per second", fontsize=_BIG)
    ax1.set_ylabel("tokens / second", fontsize=_MED)
    ax1.annotate("higher = faster", xy=(0.98, 0.06), xycoords="axes fraction",
                 ha="right", fontsize=_MED, color="#555555")
    ax1.grid(axis="y", alpha=0.25)
    ax2.bar(x, mems, color=[_color_of(k) for k in keys], width=0.55)
    ax2.set_xticks(x)
    ax2.set_xticklabels([VARIANT_SHORT[k] for k in keys], fontsize=13)
    ax2.set_title("Memory: GPU memory needed", fontsize=_BIG)
    ax2.set_ylabel("megabytes of GPU memory", fontsize=_MED)
    ax2.annotate("lower = less memory", xy=(0.98, 0.06),
                 xycoords="axes fraction", ha="right", fontsize=_MED,
                 color="#555555")
    ax2.grid(axis="y", alpha=0.25)
    fig.suptitle("Efficiency: what each recipe costs in speed and memory",
                 fontsize=17, y=1.02)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_convergence(summaries: List[dict], threshold: float, out_path: str,
                     dataset_name: str = "") -> str:
    """Horizontal bars: tokens needed to reach a fixed loss threshold.

    Directly answers 'did RoPE reach the same quality with fewer tokens?'
    in a way anyone can read: shorter bar = learned faster.
    """
    import csv
    keys, tokens_needed = [], []
    for s in summaries:
        csv_path = os.path.join(s["run_dir"], "metrics.csv")
        reached = None
        if os.path.exists(csv_path):
            with open(csv_path, newline="", encoding="utf-8") as f:
                for row in csv.DictReader(f):
                    try:
                        if float(row["val_loss"]) <= threshold:
                            reached = int(row["tokens_seen"])
                            break
                    except (ValueError, KeyError):
                        continue
        keys.append(_variant_key(s))
        tokens_needed.append(reached)
    fig, ax = plt.subplots(figsize=(10, 5))
    y = np.arange(len(keys))[::-1]
    bars = []
    for i, (key, tok) in enumerate(zip(keys, tokens_needed)):
        if tok is None:
            bars.append(ax.barh(y[i], 1.0, color="#BBBBBB"))
            ax.text(1.05, y[i], "did not reach it", va="center", fontsize=11,
                    color="#555555")
        else:
            bars.append(ax.barh(y[i], tok, color=_color_of(key), height=0.6))
            ax.text(tok * 1.01, y[i], f"{tok:,} tokens", va="center",
                    fontsize=11)
    ax.set_yticks(y)
    ax.set_yticklabels([_label_of(k) for k in keys], fontsize=11)
    ax.set_xlabel("tokens read before reaching the goal", fontsize=_MED)
    ax.set_title(
        f"How much reading before reaching loss {threshold}?\n"
        f"(shorter bar = learned faster on {dataset_name or 'this data'})",
        fontsize=_BIG, pad=12)
    ax.annotate("shorter = faster learning", xy=(0.98, 0.06),
                xycoords="axes fraction", ha="right", fontsize=_MED,
                color="#555555")
    ax.grid(axis="x", alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_verdict_card(summaries: List[dict], out_path: str,
                      dataset_name: str = "") -> str:
    """THE poster: 2x2 matrix of the four recipes + winner headline.

    One glance answers: which recipe won, by how much, and why (its cell
    shows quality + speed + memory numbers).
    """
    by_key: Dict[str, dict] = {}
    for s in summaries:
        by_key[_variant_key(s)] = s
    order = ["vanilla_learned", "vanilla_rope", "flash_learned", "flash_rope"]
    fig = plt.figure(figsize=(12, 8.5))
    gs = fig.add_gridspec(2, 2, height_ratios=[1, 1])
    vals = [by_key[k].get("best_val_loss", 0.0) for k in order if k in by_key]
    best_key = order[int(np.argmin(vals))] if vals else None
    for k, (row, col) in zip(order, [(0, 0), (0, 1), (1, 0), (1, 1)]):
        ax = fig.add_subplot(gs[row, col])
        entry = by_key.get(k)
        ax.axis("off")
        ax.set_facecolor("#F7F7F7")
        if entry is None:
            ax.text(0.5, 0.5, "not run yet", ha="center", va="center",
                    fontsize=14, color="#999999")
            continue
        win = (k == best_key)
        title_col = "#B8860B" if win else _color_of(k)
        ax.text(0.5, 0.86, _label_of(k), ha="center", va="center",
                fontsize=15, color=title_col, weight="bold")
        ppl = entry.get("val_ppl", 0.0)
        ax.text(0.5, 0.62, f"mistake level: {entry.get('best_val_loss', 0.0):.3f}",
                ha="center", fontsize=13)
        ax.text(0.5, 0.47,
                f"~{ppl:.0f} choices per word", ha="center", fontsize=12,
                color="#555555")
        ax.text(0.5, 0.32, f"speed: {entry.get('tokens_per_sec', 0.0):,.0f} tok/s",
                ha="center", fontsize=12)
        ax.text(0.5, 0.20,
                f"memory: {entry.get('peak_gpu_mem_mb', 0.0):,.0f} MB",
                ha="center", fontsize=12)
        if win:
            ax.text(0.5, 0.05, "WINNER", ha="center", fontsize=16,
                    color="#B8860B", weight="bold")
            for spine in ax.spines.values():
                spine.set_color("#B8860B")
                spine.set_linewidth(4)
    fig.suptitle(
        f"The four recipes at a glance - {dataset_name or 'the text'}",
        fontsize=19, y=0.985)
    fig.text(0.5, 0.955,
             "Lower mistake level wins. Speed and memory show what the win costs.",
             ha="center", fontsize=13, color="#555555")
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    return _save(fig, out_path)


def plot_all_comparisons(summaries: List[dict], out_dir: str,
                         dataset_name: str = "",
                         threshold: float = 2.0) -> Dict[str, str]:
    """Render the full layman comparison suite; returns path dict."""
    out = {
        "quality": plot_comparison_quality(
            summaries, os.path.join(out_dir, "01_which_recipe_learned_best.png"),
            dataset_name),
        "efficiency": plot_comparison_efficiency(
            summaries, os.path.join(out_dir, "02_speed_and_memory.png")),
        "convergence": plot_convergence(
            summaries, threshold,
            os.path.join(out_dir, "03_learning_speed.png"), dataset_name),
        "verdict": plot_verdict_card(
            summaries, os.path.join(out_dir, "04_verdict_card.png"),
            dataset_name),
    }
    return out
