"""Layman-facing visualizations.

WHAT
----
Every figure here is designed so a NON-engineer can read it in 5 seconds:
    - one idea per chart
    - plain-English titles ("Which recipe learned the language best?")
    - explicit hints on the chart ("lower = better", "higher = faster")
    - concept cartoons for attention / RoPE / FlashAttention / BPE that
      show WHAT is computed, not formulas

WHY
----
The research goal is answering "WHY did the number change?" - and the
evidence only persuades if people who cannot read the code can read the
result. These charts are the lab's external interface.

WHERE
-----
Generated by the trainer (loss curves), by scripts/analyze.py (comparison
suite) and by notebooks/04_experiment_analysis.ipynb. All outputs are
PNG files saved next to the data they describe.
"""
from __future__ import annotations

import math
import os
from typing import Dict, List, Optional

import matplotlib
matplotlib.use("Agg")  # headless-safe everywhere (Colab/Kaggle/local)
import matplotlib.pyplot as plt
import numpy as np

# Colorblind-friendly palette, fixed so charts are comparable across runs.
PALETTE = {
    "vanilla_learned": "#0072B2",   # blue   - A: classic + position table
    "vanilla_rope": "#D55E00",      # orange - B: classic + rotation
    "flash_learned": "#009E73",     # green  - C: flash + position table
    "flash_rope": "#CC79A7",        # purple - D: flash + rotation
}
VARIANT_LABELS = {
    "vanilla_learned": "A: Classic attention\n+ position table",
    "vanilla_rope": "B: Classic attention\n+ rotation (RoPE)",
    "flash_learned": "C: Flash attention\n+ position table",
    "flash_rope": "D: Flash attention\n+ rotation (RoPE)",
}
VARIANT_SHORT = {
    "vanilla_learned": "A", "vanilla_rope": "B",
    "flash_learned": "C", "flash_rope": "D",
}
_BIG = 16
_MED = 12


def _variant_key(entry: dict) -> str:
    # Normalize attention: the A/B/C/D labels treat flash_tiled and
    # flash_fused as the same experimental CELL (flash attention) - they
    # differ only in implementation, not in the ablation variable.
    attn = entry["attention"]
    if attn.startswith("flash"):
        attn = "flash"
    return f"{attn}_{entry['position']}"


def _color_of(key: str) -> str:
    return PALETTE.get(key, "#777777")


def _label_of(key: str) -> str:
    return VARIANT_LABELS.get(key, key.replace("_", " + "))


# --------------------------------------------------------------------------
# Study-dimension grouping (ABLATION_PLAN: three studies, one chart engine)
# --------------------------------------------------------------------------
# The five variables a run can differ in. The collected set of runs
# determines WHICH ones are plotted: charts auto-adapt to Study A
# (attention/position), Study B (activation), or Study C (optimizer).
_STUDY_DIMS = ["attention", "position", "activation", "swiglu_matched",
               "optimizer"]

_HUMAN = {
    "position": {"learned": "position table", "rope": "RoPE",
                 "none": "no position"},
    "activation": {"gelu": "GELU", "relu": "ReLU", "silu": "SiLU",
                   "swiglu": "SwiGLU"},
}


def _norm_value(s: dict, dim: str) -> str:
    """Canonical string for one run's value of one study dimension."""
    v = s.get(dim)
    if dim == "attention" and str(v).startswith("flash"):
        return "flash_fused"  # tiled/fused = same experimental cell
    if dim == "swiglu_matched":
        return str(bool(v))
    return str(v)


def _group_key(s: dict, dims: List[str]) -> tuple:
    return tuple(_norm_value(s, d) for d in dims)


def _group_label(key: tuple, dims: List[str]) -> str:
    """Plain-English label for a group (used as chart labels)."""
    parts = []
    for dim, val in zip(dims, key):
        if dim == "attention":
            parts.append("Flash attention" if val.startswith("flash")
                         else "Classic attention")
        elif dim == "position":
            parts.append(_HUMAN["position"].get(val, val))
        elif dim == "activation":
            parts.append(_HUMAN["activation"].get(val, val))
        elif dim == "swiglu_matched":
            parts.append("param-matched" if val == "True" else "native width")
        elif dim == "optimizer":
            parts.append("AdamW" if val == "adamw" else "Adam")
    return " + ".join(parts) if parts else str(key)


def _group_summaries(summaries: List[dict]):
    """Group runs by the dimensions that actually vary; returns
    (dims, groups, order). Runs sharing a group differ only by seed (or are
    duplicates), so group aggregates are seed means."""
    dims = [d for d in _STUDY_DIMS
            if len({str(s.get(d)) for s in summaries}) > 1]
    if not dims:
        dims = ["attention", "position"]  # default: the classic A/B/C/D view
    groups: Dict[tuple, List[dict]] = {}
    order: List[tuple] = []
    for s in summaries:
        k = _group_key(s, dims)
        if k not in groups:
            groups[k] = []   # initialize BEFORE order so the pair is atomic
            order.append(k)
        groups[k].append(s)
    return dims, groups, order


def _mean(entries: List[dict], field: str) -> float:
    vals = [e.get(field, 0.0) for e in entries if e.get(field) is not None]
    return float(np.mean(vals)) if vals else 0.0


def _group_colors(order: List[tuple], dims: List[str]) -> List[str]:
    """Deterministic per-group colors: the fixed A/B/C/D palette when the
    chart IS the attention study, else a fixed cycle of the same colors."""
    palette = list(PALETTE.values())
    colors = []
    for i, key in enumerate(order):
        if set(dims) == {"attention", "position"}:
            attn = "flash" if key[dims.index("attention")].startswith("flash") \
                else "vanilla"
            pos = key[dims.index("position")]
            colors.append(PALETTE.get(f"{attn}_{pos}", "#777777"))
        else:
            colors.append(palette[i % len(palette)])
    return colors


def _save(fig, path: str) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return path


# --------------------------------------------------------------------------
# 1. Loss curves - the basic training progress picture
# --------------------------------------------------------------------------
def plot_loss_curves_layman(run_dir: str, out_path: Optional[str] = None) -> Optional[str]:
    """Train/val loss vs tokens with plain-English annotations."""
    csv_path = os.path.join(run_dir, "metrics.csv")
    if not os.path.exists(csv_path):
        return None
    import csv
    # Per-field parse: the final evaluation row has val_loss but no
    # train_loss, so each curve tracks its own token axis (shared lists
    # would either crash on mismatched lengths or drop valid points).
    t_tok, t_loss, v_tok, v_loss = [], [], [], []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                tok = int(row["tokens_seen"])
            except (ValueError, KeyError):
                continue
            try:
                t_loss.append(float(row["train_loss"]))
                t_tok.append(tok)
            except (ValueError, KeyError):
                pass
            try:
                v_loss.append(float(row["val_loss"]))
                v_tok.append(tok)
            except (ValueError, KeyError):
                pass
    if not v_tok:
        return None
    if out_path is None:
        out_path = os.path.join(run_dir, "learning_progress.png")
    fig, ax = plt.subplots(figsize=(9, 5.5))
    if t_tok:
        ax.plot(t_tok, t_loss, color="#0072B2", lw=2.5,
                label="learning curve (training)")
    ax.plot(v_tok, v_loss, color="#D55E00", lw=2.5,
            label="checkup curve (unseen text)")
    ax.set_xlabel("amount of text read (tokens)", fontsize=_MED)
    ax.set_ylabel("mistake level (loss)", fontsize=_MED)
    ax.set_title("The model makes fewer mistakes as it reads more text",
                 fontsize=_BIG, pad=12)
    ax.annotate("lower = better", xy=(0.98, 0.9), xycoords="axes fraction",
                ha="right", fontsize=_MED, color="#555555")
    ax.legend(fontsize=_MED, frameon=False)
    ax.grid(alpha=0.25)
    ax.set_ylim(0, None)
    fig.tight_layout()
    return _save(fig, out_path)


# --------------------------------------------------------------------------
# 2. Concept cartoons - one idea each
# --------------------------------------------------------------------------
def plot_attention_concept(out_path: str) -> str:
    """WHAT attention does, in three panels, no formulas.

    Panel 1: compare - score how useful each EARLIER word is for now.
    Panel 2: normalize - turn scores into percentages (softmax).
    Panel 3: gather - blend earlier words' meanings by those percentages.
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6))
    words = ["The", "cat", "sat", "on", "the", "mat"]
    n = len(words)
    for ax, title, sub in zip(
            axes,
            ["1. COMPARE", "2. TURN INTO %", "3. GATHER"],
            ["How useful is each\nearlier word for\nreading the next one?",
             "Convert the scores into\npercentages that add up\nto 100%.",
             "Blend the earlier words'\nmeanings by those\npercentages."]):
        ax.set_xlim(-0.5, n - 0.5)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.set_title(title, fontsize=_BIG, color="#0072B2")
        if title.startswith("1."):
            heights = np.linspace(0.15, 0.9, n)
            for i, (w, h) in enumerate(zip(words, heights)):
                ax.bar(i, h, color="#66A6CC", alpha=0.9)
                ax.text(i, h + 0.05, f"{h:.0%}", ha="center", fontsize=10)
        elif title.startswith("2."):
            vals = np.linspace(0.05, 0.45, n)
            vals = vals / vals.sum()
            for i, (w, v) in enumerate(zip(words, vals)):
                ax.bar(i, v, color="#D55E00", alpha=0.9)
                ax.text(i, v + 0.05, f"{v:.0%}", ha="center", fontsize=10)
        else:
            sizes = np.linspace(400, 1200, n)
            for i, (w, s) in enumerate(zip(words, sizes)):
                ax.scatter([i], [0.5], s=s, color="#009E73", alpha=0.85)
                ax.text(i, 0.5, w, ha="center", va="center", fontsize=10,
                        color="white")
            ax.text(n - 0.5, 0.9, "size = share of\nattention", ha="center",
                    fontsize=10, color="#009E73")
        for i, w in enumerate(words):
            ax.text(i, -0.02, w, ha="center", fontsize=11)
        ax.text(0, -0.16, sub, ha="left", fontsize=_MED, color="#333333")
    fig.suptitle("How attention works: every word looks back, scores its "
                 "neighbours, and blends their meanings",
                 fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_rope_concept(out_path: str) -> str:
    """RoPE cartoon: position = rotation angle.

    Left: one token's arrow rotated differently for each position in the
    sentence. Right: two arrows whose angle difference stays the SAME for
    the same distance apart - that constant difference is how the model
    "sees" relative position.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5))
    # Left: absolute rotation grows with position
    ax = axes[0]
    ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2)
    ax.axhline(0, color="grey", lw=0.5); ax.axvline(0, color="grey", lw=0.5)
    for pos in range(6):
        ang = pos * 0.55
        x, y = np.cos(ang), np.sin(ang)
        ax.arrow(0, 0, x, y, head_width=0.06, head_length=0.08,
                 fc=PALETTE["vanilla_rope"], ec=PALETTE["vanilla_rope"],
                 lw=2, length_includes_head=True)
        ax.text(x * 1.22, y * 1.22, f"word {pos}", fontsize=11, ha="center",
                color="#D55E00")
    ax.set_title("Each position = a different\nrotation of the same arrow",
                 fontsize=_BIG, color="#D55E00")
    ax.set_aspect("equal"); ax.axis("off")
    # Right: relative angle is constant for the same distance
    ax = axes[1]
    ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2)
    ax.axhline(0, color="grey", lw=0.5); ax.axvline(0, color="grey", lw=0.5)
    for pos, col in [(2, "#0072B2"), (5, "#D55E00")]:
        ang = pos * 0.55
        ax.arrow(0, 0, np.cos(ang), np.sin(ang), head_width=0.06,
                 head_length=0.08, fc=col, ec=col, lw=2.5,
                 length_includes_head=True)
        ax.text(np.cos(ang) * 1.2, np.sin(ang) * 1.2,
                f"word {pos}", fontsize=11, ha="center", color=col)
    arc = plt.Arc((0, 0), 0.7, 0.7, angle=0, theta1=0, theta2=150,
                  color="#555555", lw=1.5, linestyle="--")
    ax.add_patch(arc)
    ax.text(0.55, 0.55, "same angle gap\n= same distance\napart", fontsize=11,
            ha="center", color="#555555")
    ax.set_title("Words the same distance apart\nalways see the same angle gap",
                 fontsize=_BIG, color="#0072B2")
    ax.set_aspect("equal"); ax.axis("off")
    fig.suptitle("Rotation positions (RoPE): where a word sits = how far its "
                 "meaning-arrow is turned", fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_flash_concept(out_path: str) -> str:
    """FlashAttention cartoon: giant score table vs one strip at a time.

    Left: the classic method materializes the FULL T x T comparison table
    (red, expensive). Right: flash works strip by strip, keeping only one
    strip in memory and updating a running result (green, cheap). Same
    final answer - the strip method is algebraically exact.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.2))
    T = 10
    grid = np.ones((T, T))
    ax = axes[0]
    ax.imshow(grid, cmap="Reds", vmin=0, vmax=1, interpolation="nearest")
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_xlabel("words so far", fontsize=_MED)
    ax.set_ylabel("current word", fontsize=_MED)
    ax.set_title("Classic attention: builds the\nWHOLE comparison table at once",
                 fontsize=_BIG, color="#8B0000")
    ax.text(0.5, -0.16, "10 x 10 = 100 boxes to remember", transform=ax.transAxes,
            ha="center", fontsize=_MED, color="#8B0000")
    ax = axes[1]
    ax.imshow(np.tril(np.ones((T, T))), cmap="Greens", vmin=0, vmax=1,
              interpolation="nearest")
    for j in range(T):
        ax.axvline(j + 0.5, color="white", lw=2.5)
    ax.axvspan(2.5, 3.5, color="#CC79A7", alpha=0.55)
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_xlabel("words so far", fontsize=_MED)
    ax.set_ylabel("current word", fontsize=_MED)
    ax.set_title("Flash attention: works through\nONE strip at a time",
                 fontsize=_BIG, color="#006400")
    ax.text(0.5, -0.16, "only 1 strip in memory at any moment",
            transform=ax.transAxes, ha="center", fontsize=_MED,
            color="#006400")
    ax.text(3, -1.6, "in use now", ha="center", fontsize=10, color="#CC79A7")
    fig.suptitle("FlashAttention: same final answer, far less memory - the "
                 "table is processed strip by strip", fontsize=17, y=1.02)
    return _save(fig, out_path)


def plot_bpe_concept(text: str, tokenizer, out_path: str) -> str:
    """BPE cartoon: how a sentence is chopped into reusable pieces.

    Each token is drawn as a coloured box; frequent words become ONE box,
    rare words get split into several smaller (still reusable) pieces.
    Caption states the compression: N characters -> M pieces.
    """
    ids = tokenizer.encode(text)
    pieces = [tokenizer.decode([i]) for i in ids]
    fig, ax = plt.subplots(figsize=(max(8, len(pieces) * 0.55), 3.6))
    ax.axis("off")
    x = 0.0
    cmap = plt.get_cmap("tab20")
    for k, piece in enumerate(pieces):
        w = max(0.32, len(piece) * 0.16)
        ax.add_patch(plt.Rectangle((x, 0.3), w - 0.03, 0.6,
                                   facecolor=cmap(k % 20), alpha=0.85,
                                   edgecolor="black"))
        ax.text(x + (w - 0.03) / 2, 0.6, piece.replace(" ", "␣"),
                ha="center", va="center", fontsize=10)
        x += w
    ax.set_xlim(0, x)
    ax.set_ylim(0, 1.1)
    ratio = len(text) / max(len(ids), 1)
    ax.text(0, -0.12,
            f"{len(text)} characters -> {len(ids)} reusable pieces "
            f"(each piece ~{ratio:.1f} characters)",
            fontsize=_MED, color="#333333")
    ax.set_title("How the tokenizer chops text into reusable pieces (BPE)",
                 fontsize=_BIG)
    return _save(fig, out_path)


# --------------------------------------------------------------------------
# 3. Comparison charts (the scientific core, rendered for everyone)
# --------------------------------------------------------------------------
def plot_comparison_quality(summaries: List[dict], out_path: str,
                            dataset_name: str = "") -> str:
    """Bar chart: best validation loss per variant, winner highlighted.

    'Lower = better' printed ON the chart. Ties are REAL science here, not
    a display bug: flash == vanilla numerically, so B/D (or A/C) often tie
    EXACTLY - every tied bar gets a star, none is crowned arbitrarily.

    Multiple seeds (ABLATION_PLAN section 21): bars become mean ± std over
    seeds, so a 0.01 loss difference that is smaller than the seed spread
    is visibly NOT a real difference.
    """
    seeds = sorted({s["seed"] for s in summaries})
    multi_seed = len(seeds) > 1
    dims, groups, order = _group_summaries(summaries)
    keys = [_group_label(k, dims) for k in order]
    vals = [_mean(groups[k], "best_val_loss") for k in order]
    stds = ([float(np.std([s.get("best_val_loss", 0.0) for s in groups[k]]))
             for k in order] if multi_seed else None)
    fig, ax = plt.subplots(figsize=(10, 5.8))
    x = np.arange(len(vals))
    colors = _group_colors(order, dims)
    bars = ax.bar(x, vals, yerr=stds if multi_seed else None, capsize=6,
                  color=colors, width=0.55,
                  error_kw={"ecolor": "#555555", "elinewidth": 1.5})
    # Winners = every group at (or within 1e-9 of) the best loss. The
    # previous single-argmin star silently picked the FIRST tied group -
    # which mislabelled flash+RoPE's exact tie with vanilla+RoPE.
    best_val = min(vals)
    winners = [i for i, v in enumerate(vals) if abs(v - best_val) < 1e-9]
    for i in winners:
        ax.scatter([i], [vals[i]], marker="*", s=420, color="#FFD700",
                   edgecolor="black", zorder=5)
    label = "winner" if len(winners) == 1 else "winners (exact tie)"
    ax.scatter([], [], marker="*", s=420, color="#FFD700",
               edgecolor="black", label=label)
    ax.set_xticks(x)
    ax.set_xticklabels(keys, fontsize=10.5, rotation=12, ha="right")
    ax.set_ylabel("mistake level (best validation loss)", fontsize=_MED)
    title = f"Which recipe learned {dataset_name or 'the text'} best?"
    if multi_seed:
        title += f"\n(mean ± std over {len(seeds)} seeds)"
    ax.set_title(title, fontsize=_BIG, pad=12)
    ax.annotate("lower = better", xy=(0.98, 0.06), xycoords="axes fraction",
                ha="right", fontsize=_MED, color="#555555")
    for i, v in enumerate(vals):
        ax.text(i, v + 0.01 * max(vals), f"{v:.3f}", ha="center", fontsize=11)
    # Legend BELOW the chart (ncol=2): never overlaps the bars/star again.
    ax.legend(fontsize=_MED, loc="upper center",
              bbox_to_anchor=(0.5, -0.10), ncol=2, frameon=False)
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_comparison_efficiency(summaries: List[dict], out_path: str) -> str:
    """Two bars per group: speed (higher=better) and memory (lower=better)."""
    dims, groups, order = _group_summaries(summaries)
    keys = [_group_label(k, dims) for k in order]
    speeds = [_mean(groups[k], "tokens_per_sec") for k in order]
    mems = [_mean(groups[k], "peak_gpu_mem_mb") for k in order]
    colors = _group_colors(order, dims)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13.5, 5.8))
    x = np.arange(len(keys))
    ax1.bar(x, speeds, color=colors, width=0.55)
    ax1.set_xticks(x)
    ax1.set_xticklabels(keys, fontsize=10, rotation=22, ha="right")
    ax1.set_title("Speed: text read per second", fontsize=_BIG)
    ax1.set_ylabel("tokens / second", fontsize=_MED)
    ax1.annotate("higher = faster", xy=(0.98, 0.06), xycoords="axes fraction",
                 ha="right", fontsize=_MED, color="#555555")
    ax1.grid(axis="y", alpha=0.25)
    ax2.bar(x, mems, color=colors, width=0.55)
    ax2.set_xticks(x)
    ax2.set_xticklabels(keys, fontsize=10, rotation=22, ha="right")
    ax2.set_title("Memory: GPU memory needed", fontsize=_BIG)
    ax2.set_ylabel("megabytes of GPU memory", fontsize=_MED)
    ax2.annotate("lower = less memory", xy=(0.98, 0.06),
                 xycoords="axes fraction", ha="right", fontsize=_MED,
                 color="#555555")
    ax2.grid(axis="y", alpha=0.25)
    fig.suptitle("Efficiency: what each recipe costs in speed and memory",
                 fontsize=17, y=1.03)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_convergence(summaries: List[dict], threshold: float, out_path: str,
                     dataset_name: str = "") -> str:
    """Horizontal bars: tokens needed to reach a fixed loss threshold.

    Directly answers 'did RoPE reach the same quality with fewer tokens?'
    in a way anyone can read: shorter bar = learned faster. Multiple seeds
    in a group are averaged; groups that never reached the threshold are
    drawn grey.
    """
    import csv
    dims, groups, order = _group_summaries(summaries)
    keys = [_group_label(k, dims) for k in order]
    tokens_needed: List = []
    for k in order:
        reached_per_seed = []
        for s in groups[k]:
            csv_path = os.path.join(s["run_dir"], "metrics.csv")
            reached = None
            if os.path.exists(csv_path):
                with open(csv_path, newline="", encoding="utf-8") as f:
                    for row in csv.DictReader(f):
                        try:
                            if float(row["val_loss"]) <= threshold:
                                reached = int(row["tokens_seen"])
                                break
                        except (ValueError, KeyError):
                            continue
            if reached is not None:
                reached_per_seed.append(reached)
        tokens_needed.append(float(np.mean(reached_per_seed))
                             if reached_per_seed else None)
    colors = _group_colors(order, dims)
    fig, ax = plt.subplots(figsize=(10, 5))
    y = np.arange(len(keys))[::-1]
    for i, (key, tok) in enumerate(zip(keys, tokens_needed)):
        if tok is None:
            ax.barh(y[i], 1.0, color="#BBBBBB")
            ax.text(1.05, y[i], "did not reach it", va="center", fontsize=11,
                    color="#555555")
        else:
            ax.barh(y[i], tok, color=colors[i], height=0.6)
            ax.text(tok * 1.01, y[i], f"{tok:,.0f} tokens", va="center",
                    fontsize=11)
    ax.set_yticks(y)
    ax.set_yticklabels(keys, fontsize=11)
    ax.set_xlabel("tokens read before reaching the goal", fontsize=_MED)
    ax.set_title(
        f"How much reading before reaching loss {threshold}?\n"
        f"(shorter bar = learned faster on {dataset_name or 'this data'})",
        fontsize=_BIG, pad=12)
    ax.annotate("shorter = faster learning", xy=(0.98, 0.06),
                xycoords="axes fraction", ha="right", fontsize=_MED,
                color="#555555")
    ax.grid(axis="x", alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_verdict_card(summaries: List[dict], out_path: str,
                      dataset_name: str = "") -> str:
    """THE poster: one cell per study group + winner headline.

    The grid adapts to however many groups the study has (4 for Study A,
    5 for Study B, 2 for Study C). Each cell shows quality + speed +
    memory numbers; ties are honoured (flash == vanilla numerically, so
    exact ties are EXPECTED, never broken arbitrarily).

    One glance answers: which recipe won, by how much, and why.
    """
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    n = len(order)
    cols = 2 if n <= 6 else 3
    rows = math.ceil(n / cols)
    # Generous cell size: long group labels must never collide with the
    # numbers below them.
    fig = plt.figure(figsize=(6.8 * cols, 5.0 * rows))
    gs = fig.add_gridspec(rows, cols)
    vals = [_mean(groups[k], "best_val_loss") for k in order]
    # Winner set = every group at the best loss (tie-aware). The old single
    # argmin crowned the first tied group - misleading, because a
    # flash/vanilla tie is the EXPECTED, exact behaviour.
    win_indexes: List[int] = []
    if vals:
        best_val = min(vals)
        win_indexes = [i for i, v in enumerate(vals)
                       if abs(v - best_val) < 1e-9]
    tied = len(win_indexes) > 1
    for i, k in enumerate(order):
        ax = fig.add_subplot(gs[i // cols, i % cols])
        entries = groups[k]
        ax.axis("off")
        ax.set_facecolor("#F7F7F7")
        win = i in win_indexes
        title_col = "#B8860B" if win else colors[i]
        ax.text(0.5, 0.86, _group_label(k, dims), ha="center", va="center",
                fontsize=13, color=title_col, weight="bold")
        ppl = _mean(entries, "val_ppl")
        ax.text(0.5, 0.62, f"mistake level: {_mean(entries, 'best_val_loss'):.3f}",
                ha="center", fontsize=13)
        ax.text(0.5, 0.47,
                f"~{ppl:.0f} choices per word", ha="center", fontsize=12,
                color="#555555")
        ax.text(0.5, 0.32,
                f"speed: {_mean(entries, 'tokens_per_sec'):,.0f} tok/s",
                ha="center", fontsize=12)
        ax.text(0.5, 0.20,
                f"memory: {_mean(entries, 'peak_gpu_mem_mb'):,.0f} MB",
                ha="center", fontsize=12)
        if win:
            ax.text(0.5, 0.05,
                    "WINNER (tied)" if tied else "WINNER",
                    ha="center", fontsize=16, color="#B8860B", weight="bold")
            for spine in ax.spines.values():
                spine.set_color("#B8860B")
                spine.set_linewidth(4)
    fig.suptitle(
        f"The recipes at a glance - {dataset_name or 'the text'}",
        fontsize=19, y=0.985)
    if tied:
        win_groups = [order[i] for i in win_indexes]
        # A tie that spans attention backends = flash ties classic by
        # construction, and the flash version of the tie wins on cost.
        attn_vals = {k[dims.index("attention")] for k in win_groups
                     if "attention" in dims}
        if len(attn_vals) > 1:
            note = ("Exact quality tie (flash = classic by construction). "
                    "The flash version of the tie wins on speed & memory.")
        else:
            note = ("Exact quality tie - several recipes reached the same "
                    "mistake level.")
    else:
        note = "Lower mistake level wins. Speed and memory show what the win costs."
    fig.text(0.5, 0.955, note, ha="center", fontsize=13, color="#555555")
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    return _save(fig, out_path)


# --------------------------------------------------------------------------
# 4. Evaluation-battery charts (from eval_report.json - ABLATION_PLAN sec 21)
# --------------------------------------------------------------------------
def _load_eval_reports(summaries: List[dict]) -> Dict[str, dict]:
    """run_dir -> eval_report.json (only for runs that have one)."""
    import json as _json
    reports: Dict[str, dict] = {}
    for s in summaries:
        path = os.path.join(s["run_dir"], "eval_report.json")
        if os.path.exists(path):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    reports[s["run_dir"]] = _json.load(f)
            except (OSError, ValueError):
                continue
    return reports


def plot_few_shot_scaling(summaries: List[dict], out_path: str,
                          dataset_name: str = "") -> Optional[str]:
    """ICL curve: accuracy vs number of example shots (0 = zero-shot).

    The line a layman wants to see: 'with no examples the model guessed
    ~25% (chance), with 5 examples it got X right' - i.e. does the model
    actually USE the pattern shown in context? Higher = better."""
    reports = _load_eval_reports(summaries)
    if not reports:
        return None
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    fig, ax = plt.subplots(figsize=(9.5, 5.8))
    any_plotted = False
    for i, k in enumerate(order):
        entries = [e for e in groups[k] if e["run_dir"] in reports]
        shot_values = None
        for e in entries:
            fs = reports[e["run_dir"]].get("few_shot", {})
            if fs:
                shot_values = fs
                break
        if not shot_values:
            continue
        shots = [int(kk) for kk in shot_values.keys()]
        accs = [shot_values[str(kk)] for kk in shots]
        ax.plot(shots, accs, marker="o", ms=7, lw=2, color=colors[i],
                label=_group_label(k, dims))
        any_plotted = True
    if not any_plotted:
        return None
    ax.axhline(0.25, color="#BBBBBB", ls="--", lw=1.2)
    ax.text(0.02, 0.27, "random guessing (1 of 4)", fontsize=10,
            color="#888888")
    ax.set_xlabel("examples shown in the prompt (shots)", fontsize=_MED)
    ax.set_ylabel("accuracy at continuing the pattern", fontsize=_MED)
    ax.set_title(f"Zero / one / few-shot learning on {dataset_name or 'the data'}",
                 fontsize=_BIG, pad=12)
    ax.annotate("higher = better", xy=(0.98, 0.06), xycoords="axes fraction",
                ha="right", fontsize=_MED, color="#555555")
    ax.set_ylim(0, 1.02)
    ax.legend(fontsize=11, loc="upper center",
              bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_calibration(summaries: List[dict], out_path: str,
                     dataset_name: str = "") -> Optional[str]:
    """Trust-meter: ECE per variant with a plain-English reading guide.

    ECE = gap between how sure the model SAYS it is and how often it is
    actually right. Lower = more trustworthy; the guide panel explains the
    scale without jargon."""
    reports = _load_eval_reports(summaries)
    if not reports:
        return None
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    plotted = []
    for k in order:
        for e in groups[k]:
            rep = reports.get(e["run_dir"], {})
            if rep.get("ece") is not None:
                plotted.append((k, float(rep["ece"])))
                break
    if not plotted:
        return None
    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(13, 5.4))
    ys = np.arange(len(plotted))[::-1]
    ax.barh(ys, [v for _, v in plotted],
            color=[colors[order.index(k)] for k, _ in plotted], height=0.55)
    ax.set_yticks(ys)
    ax.set_yticklabels([_group_label(k, dims) for k, _ in plotted],
                       fontsize=10.5)
    ax.set_xlabel("calibration error (ECE)", fontsize=_MED)
    ax.set_title("Trust-meter: does confidence match\nactual accuracy?",
                 fontsize=_BIG, pad=12)
    ax.annotate("lower = more trustworthy", xy=(0.98, 0.06),
                xycoords="axes fraction", ha="right", fontsize=_MED,
                color="#555555")
    for i2, (_, v) in enumerate(plotted):
        ax.text(v + 0.002, ys[i2], f"{v:.3f}", va="center", fontsize=10)
    ax.grid(axis="x", alpha=0.25)
    ax2.axis("off")
    ax2.set_xlim(0, 1)
    ax2.set_ylim(0, 1)
    ax2.text(0.5, 0.9, "How to read it", ha="center", fontsize=_BIG,
             weight="bold", color="#0072B2")
    lines = [
        "0.00 - 0.05 : very trustworthy",
        "0.05 - 0.15 : trustworthy",
        "0.15 - 0.30 : noticeably overconfident",
        "0.30 +      : confident but often wrong",
        "",
        "ECE measures the gap between how sure",
        "the model SAYS it is and how often it",
        "is actually right.",
    ]
    ax2.text(0.5, 0.62, "\n".join(lines), ha="center", va="top", fontsize=12,
             color="#333333")
    fig.suptitle(f"Calibration on {dataset_name or 'the data'}", fontsize=17,
                 y=1.03)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_length_robustness(summaries: List[dict], out_path: str,
                           dataset_name: str = "") -> Optional[str]:
    """Loss by context-position bucket: the long-range penalty.

    Four bars per variant = prediction quality at the START, early-middle,
    late-middle and END of the context window. A rising staircase means
    the model loses its grip at long range; a flat line means distance
    doesn't hurt it."""
    reports = _load_eval_reports(summaries)
    if not reports:
        return None
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    buckets_names = ["start", "early\nmiddle", "late\nmiddle", "end"]
    data = {}
    for k in order:
        for e in groups[k]:
            rep = reports.get(e["run_dir"], {})
            if "length_buckets" in rep:
                data[k] = rep["length_buckets"]
                break
    if not data:
        return None
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    n_buckets = len(next(iter(data.values())))
    xs = np.arange(n_buckets)
    width = 0.8 / max(len(data), 1)
    for i, k in enumerate(order):
        if k not in data:
            continue
        vals = data[k]
        ax.bar(xs + (i - (len(data) - 1) / 2) * width, vals, width=width * 0.9,
               color=colors[i], label=_group_label(k, dims))
    ax.set_xticks(xs)
    ax.set_xticklabels(buckets_names, fontsize=11)
    ax.set_xlabel("position inside the context window", fontsize=_MED)
    ax.set_ylabel("mistake level (loss)", fontsize=_MED)
    ax.set_title(f"Long-range penalty on {dataset_name or 'the data'}: "
                 "does the far end of the text stay readable?",
                 fontsize=_BIG, pad=12)
    ax.annotate("lower + flatter = better long memory", xy=(0.98, 0.06),
                xycoords="axes fraction", ha="right", fontsize=_MED,
                color="#555555")
    ax.legend(fontsize=10.5, loc="upper center",
              bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_quality_vs_cost(summaries: List[dict], out_path: str,
                         dataset_name: str = "") -> Optional[str]:
    """Quality vs compute bill (ABLATION_PLAN section 21).

    x = FLOPs spent training (tokens x flops/token), y = best val loss.
    The winner is the point in the LOWER-LEFT: best quality per FLOP.
    """
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    fig, ax = plt.subplots(figsize=(9.5, 6))
    any_plotted = False
    for i, k in enumerate(order):
        entries = groups[k]
        flops = [e.get("tokens_seen", 0) * 6 * e.get("num_params", 0)
                 for e in entries if e.get("num_params")]
        losses = [e.get("best_val_loss") for e in entries if e.get("num_params")]
        if not flops or not losses:
            continue
        ax.scatter(flops, losses, s=120, color=colors[i], zorder=5,
                   label=_group_label(k, dims))
        any_plotted = True
    if not any_plotted:
        return None
    ax.set_xlabel("compute bill (FLOPs spent training)", fontsize=_MED)
    ax.set_ylabel("mistake level (best validation loss)", fontsize=_MED)
    ax.set_title(f"Quality vs compute on {dataset_name or 'the data'}: "
                 "lower-left corner wins", fontsize=_BIG, pad=12)
    ax.annotate("best value", xy=(0.02, 0.06), xycoords="axes fraction",
                fontsize=_MED, color="#555555")
    ax.legend(fontsize=11, loc="upper center",
              bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    return _save(fig, out_path)


def plot_overfit_check(summaries: List[dict], out_path: str,
                       dataset_name: str = "") -> Optional[str]:
    """THE OVERFIT DETECTOR: train vs validation loss per variant, in EPOCHS.

    Overfitting is a function of EPOCHS (passes over the training set),
    not tokens - a 65M-token budget can be 4 healthy epochs (TinyStories)
    or 260 memorization epochs (Shakespeare). Each panel plots both curves
    on the epoch axis; the fork (train keeps falling, validation turns and
    climbs) is the overfit signature. Panels get a red OVERFIT badge when
    the val-train gap at the end exceeds 0.5 (matching summary.json's
    overfit_signal rule), and the gap is printed on every panel.

    HOW to read it: two lines together and falling = healthy. Lines
    FORK apart = the model is memorizing, not learning. Badge = the run
    is invalid for quality ranking; use best.pt / early evals only."""
    import csv
    import json as _json
    dims, groups, order = _group_summaries(summaries)
    colors = _group_colors(order, dims)
    panels = []
    for k in order:
        s = groups[k][0]  # first seed: the shape of the story
        csv_path = os.path.join(s["run_dir"], "metrics.csv")
        if not os.path.exists(csv_path):
            continue
        tokens, train_l, val_l = [], [], []
        with open(csv_path, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                try:
                    t = int(row["tokens_seen"])
                    tr = float(row["train_loss"])
                    v = float(row["val_loss"])
                except (ValueError, KeyError):
                    continue  # final rows carry val only: need BOTH curves
                tokens.append(t)
                train_l.append(tr)
                val_l.append(v)
        if not tokens:
            continue
        train_tokens = 1
        meta_path = os.path.join(s["run_dir"], "meta.json")
        if os.path.exists(meta_path):
            try:
                with open(meta_path, "r", encoding="utf-8") as f:
                    train_tokens = max(_json.load(f).get("train_tokens", 1), 1)
            except (OSError, ValueError):
                pass
        epochs = [t / train_tokens for t in tokens]
        gap = val_l[-1] - train_l[-1]
        panels.append((k, _group_label(k, dims), epochs, train_l, val_l,
                       gap, colors[order.index(k)]))
    if not panels:
        return None
    n = len(panels)
    cols = 2 if n <= 6 else 3
    rows = math.ceil(n / cols)
    fig, axes = plt.subplots(rows, cols, figsize=(6.6 * cols, 4.4 * rows),
                             squeeze=False)
    for i, (k, label, epochs, train_l, val_l, gap, color) in enumerate(panels):
        ax = axes[i // cols, i % cols]
        ax.plot(epochs, train_l, color="#0072B2", lw=2,
                label="training")
        ax.plot(epochs, val_l, color="#D55E00", lw=2,
                label="validation")
        ax.fill_between(epochs, train_l, val_l, alpha=0.12, color="#888888")
        ax.set_title(label, fontsize=11.5, color=color, weight="bold")
        ax.set_xlabel("epochs over the training set", fontsize=9.5)
        ax.set_ylabel("loss", fontsize=9.5)
        badge = gap > 0.5
        ax.text(0.98, 0.94,
                f"gap: {gap:.2f}" + ("  OVERFIT" if badge else "  ok"),
                transform=ax.transAxes, ha="right", va="top", fontsize=10.5,
                color="#8B0000" if badge else "#006400", weight="bold",
                bbox=dict(facecolor="white", alpha=0.85, edgecolor="none"))
        ax.grid(alpha=0.25)
    for i in range(n, rows * cols):
        axes[i // cols, i % cols].axis("off")
    handles = [plt.Line2D([], [], color="#0072B2", lw=2),
               plt.Line2D([], [], color="#D55E00", lw=2)]
    fig.legend(handles, ["training", "validation"], loc="lower center",
               ncol=2, fontsize=11, frameon=False)
    fig.suptitle(
        f"Overfit check on {dataset_name or 'the data'}: two lines together = "
        "learning. Forking apart = memorizing.", fontsize=15.5, y=1.0)
    fig.text(0.5, 0.955,
             "The fork is the tell: training keeps falling while validation "
             "turns and climbs. Badged runs are invalid for quality ranking.",
             ha="center", fontsize=11.5, color="#555555")
    fig.tight_layout(rect=[0, 0, 1, 0.94])
    return _save(fig, out_path)


def plot_eval_reports(summaries: List[dict], out_dir: str,
                      dataset_name: str = "") -> Dict[str, str]:
    """Render the evaluation-battery charts (05-08); skips gracefully when
    runs have no eval_report.json yet (run scripts/evaluate.py first)."""
    rendered = {}
    jobs = {
        "few_shot": (plot_few_shot_scaling,
                     os.path.join(out_dir, "05_few_shot_learning.png")),
        "calibration": (plot_calibration,
                        os.path.join(out_dir, "06_trust_and_calibration.png")),
        "length": (plot_length_robustness,
                   os.path.join(out_dir, "07_long_range_memory.png")),
        "cost": (plot_quality_vs_cost,
                 os.path.join(out_dir, "08_quality_vs_cost.png")),
    }
    for name, (fn, path) in jobs.items():
        try:
            p = fn(summaries, path, dataset_name)
            if p:
                rendered[name] = p
        except Exception:
            continue  # one bad chart must never hide the others
    return rendered


def plot_all_comparisons(summaries: List[dict], out_dir: str,
                         dataset_name: str = "",
                         threshold: float = 2.0) -> Dict[str, str]:
    """Render the full layman comparison suite; returns path dict.

    Empty summaries (no completed runs) render nothing instead of crashing:
    the analysis caller prints the 'train first' message."""
    if not summaries:
        return {}
    out = {
        "quality": plot_comparison_quality(
            summaries, os.path.join(out_dir, "01_which_recipe_learned_best.png"),
            dataset_name),
        "efficiency": plot_comparison_efficiency(
            summaries, os.path.join(out_dir, "02_speed_and_memory.png")),
        "convergence": plot_convergence(
            summaries, threshold,
            os.path.join(out_dir, "03_learning_speed.png"), dataset_name),
        "verdict": plot_verdict_card(
            summaries, os.path.join(out_dir, "04_verdict_card.png"),
            dataset_name),
        "overfit": plot_overfit_check(
            summaries, os.path.join(out_dir, "09_overfit_check.png"),
            dataset_name),
    }
    return out
