"""TinyStories preparation (Dataset 2 - natural language check).

WHAT
----
Downloads the TinyStories corpus (children's stories generated by GPT-3.5/
GPT-4, published by Eldan & Li 2023) from HuggingFace as flat text:
    TinyStories-train.txt (~2.2GB) and TinyStories-valid.txt.
Uses the configured SUBSET limits (default 50MB train / 2MB val - the plan
demands a controlled, documented subset first), then the shared BPE
pipeline (data/download.py).

WHY
----
Shakespeare verifies the machinery; TinyStories tests whether the A/B/C/D
observations survive on natural, varied language (plan section 20). It is
also where the tokenizer and data pipeline get stressed - 50MB of raw text
is ~100x the Shakespeare corpus.

WHERE
-----
Intended for the Colab/Kaggle T4 tier; on the local machine only tiny limits make
sense (set train_limit_chars: 2_000_000 to keep local runs fast).
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from data.download import download_file, prepare_common  # noqa: E402
from src.utils.config import load_dataset_config  # noqa: E402
from src.utils.environment import data_dir  # noqa: E402

TRAIN_URL = ("https://huggingface.co/datasets/roneneldan/TinyStories/"
             "resolve/main/TinyStories-train.txt")
VAL_URL = ("https://huggingface.co/datasets/roneneldan/TinyStories/"
           "resolve/main/TinyStories-valid.txt")


def prepare(config: dict) -> dict:
    """Download (subset) + prepare; returns the trainer's data dict."""
    name = config["dataset"]
    ddir = os.path.join(data_dir(), name)
    train_path = os.path.join(ddir, "train.txt")
    val_path = os.path.join(ddir, "val.txt")

    if not os.path.exists(train_path):
        print(f"downloading TinyStories subset -> {train_path}")
        download_file(TRAIN_URL, train_path,
                      limit_chars=config.get("train_limit_chars", 50_000_000))
    if not os.path.exists(val_path):
        print(f"downloading TinyStories validation -> {val_path}")
        download_file(VAL_URL, val_path,
                      limit_chars=config.get("val_limit_chars", 2_000_000))

    return prepare_common(name, config, train_path, val_path)


if __name__ == "__main__":
    cfg = load_dataset_config("tinystories")
    out = prepare(cfg)
    print("prepared:", {k: v for k, v in out.items() if "bin" in k})
